
# Gem::Specification for Nifty-generators-0.0.3
# Originally generated by Echoe

Gem::Specification.new do |s|
  s.name = %q{nifty-generators}
  s.version = "0.0.3"

  s.specification_version = 2 if s.respond_to? :specification_version=

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bates"]
  s.date = %q{2008-05-06}
  s.description = %q{A collection of Ryan's generator scripts for Rails.}
  s.email = %q{ryan@railscasts.com}
  s.extra_rdoc_files = ["lib/nifty_generator.rb", "LICENSE", "README"]
  s.files = ["lib/nifty_generator.rb", "LICENSE", "Manifest", "rails_generators/nifty_layout/nifty_layout_generator.rb", "rails_generators/nifty_layout/templates/layout.html.erb", "rails_generators/nifty_layout/templates/stylesheet.css", "rails_generators/nifty_layout/USAGE", "rails_generators/nifty_scaffold/nifty_scaffold_generator.rb", "rails_generators/nifty_scaffold/templates/controller.rb", "rails_generators/nifty_scaffold/USAGE", "README", "test/test_generator_helper.rb", "test/test_helper.rb", "test/test_nifty_generator.rb", "test/test_nifty_layout_generator.rb", "test/test_nifty_scaffold_generator.rb", "nifty-generators.gemspec"]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/ryanb/nifty-generators}
  s.rdoc_options = ["--line-numbers", "--inline-source", "--title", "Nifty-generators", "--main", "README"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{nifty-generators}
  s.rubygems_version = %q{1.0.0}
  s.summary = %q{A collection of Ryan's generator scripts for Rails.}
  s.test_files = ["test/test_generator_helper.rb", "test/test_helper.rb", "test/test_nifty_generator.rb", "test/test_nifty_layout_generator.rb", "test/test_nifty_scaffold_generator.rb"]
end


# # Original Rakefile source (requires the Echoe gem):
# 
# require 'rubygems'
# require 'rake'
#  
# begin
#   require 'echoe'
# 
#   Echoe.new('nifty-generators', '0.0.3') do |p|
#     p.summary        = "A collection of Ryan's generator scripts for Rails."
#     p.description    = "A collection of Ryan's generator scripts for Rails."
#     p.url            = "http://github.com/ryanb/nifty-generators"
#     p.author         = 'Ryan Bates'
#     p.email          = "ryan@railscasts.com"
#     p.ignore_pattern = ["script/*", "*.gemspec"]
#   end
# 
# rescue LoadError => boom
#   puts "You are missing a dependency required for meta-operations on this gem."
#   puts "#{boom.to_s.capitalize}."
# end
# 
# desc "Build the manifest and gemspec files."
# task :build => [:build_manifest, :build_gemspec]
